apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: javascript-test-pipeline
  labels:
    apps.tanzu.vmware.com/pipeline: test
    apps.tanzu.vmware.com/language: javascript
spec:
  params:
    - name: source-url
    - name: source-revision
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
        steps:
          - name: test
            image: node:20-alpine
            script: |-
              set -ex
              cd `mktemp -d`
              curl -s $(params.source-url) | tar -m -xzvf -
              npm test